name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
          echo "GoodBye Crewl World!!!"
